version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$DST_REPO
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/$DST_REPO
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  build-and-push:
    jobs:
      - build-and-push
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          readme: README.md
          #path: path/to/Docker/build/context
          #deploy: false
          image: $DOCKER_LOGIN/$DST_REPO
          tag: latest
  nightly-build-deploy:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-push
