version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$DST_REPO
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_LOGIN/$DST_REPO
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push
