version: 2.1

executors:
  docker-build-buster:
    docker:
      - image: circleci/buildpack-deps:buster
  docker-push-files-2-dockerhub:
    docker:
    - image: gofunky/readmyhub:1.2.2-envload
    environment:
      README_PATH: /data/<< parameters.file >>
    parameters:
      file:
        default: README.md
        description: Path to the README.md file
        type: string
    working_directory: /data

jobs:
  build:
    executor: docker-build-buster
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: make docker-build
      - run:
          name: Save Docker image
          command: DOCKER_IMAGE_FILENAME=image.tar make docker-save
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test:
    executor: docker-build-buster
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Test Docker image
          command: make docker-test
  publish-dockerhub:
    executor: docker-build-buster
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Docker Hub
          command: make dockerhub-push
#  publish-quay:
#    executor: docker-build-buster
#    steps:
#      - attach_workspace:
#          at: /tmp/workspace
#      - checkout
#      - setup_remote_docker:
#          version: 18.09.3
#      - run:
#          name: Load archived Docker image
#          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
#      - run:
#          name: Push Docker image to Quay.io
#          command: make quay-push
  upload-files:
    description: Push the given README.md to the Docker Hub
    executor:
      name: docker-push-files-2-dockerhub
      file: << parameters.file >>
    parameters:
      file:
        default: README.md
        description: Path to the README.md file
        type: string
      organization:
        default: ""
        description: |
          Docker Hub organization or user name. Environment variables from envorbs are accepted. By default, the git organization is assumed.
        type: string
      repository:
        default: ""
        description: |
          Docker Hub repository name. Environment variables from envorbs are accepted. By default, the git repository name is assumed.
        type: string
    steps:
    - checkout
    - upload-files:
        organization: << parameters.organization >>
        repository: << parameters.repository >>

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-dockerhub:
          requires:
            - test
#      - publish-quay:
#          requires:
#            - test
      # Afegit per tal de pujar el readme.md (o qualsevol arxiu) a dockerhub
      - upload-files:
          requires:
            - publish-dockerhub  
  nightly-build-deploy:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-dockerhub:
          requires:
            - test
      # Afegit per tal de pujar el readme.md (o qualsevol arxiu) a dockerhub
      - upload-files:
          requires:
            - publish-dockerhub  
#      - publish-quay:
#          requires:
#            - test

# Aixo es necesari per pujar el readme.md a dockerhub
commands:
  update:
    parameters:
      organization:
        default: ""
        description: |
          Docker Hub organization or user name. Environment variables from envorbs are accepted. By default, the git organization is assumed.
        type: string
      repository:
        default: ""
        description: |
          Docker Hub repository name. Environment variables from envorbs are accepted. By default, the git repository name is assumed.
        type: string
    steps:
    - run:
        command: |
          if [ -z "$DOCKERHUB_USERNAME" ]; then
            echo "ERROR: DOCKERHUB_USERNAME is not set!"
            exit 127
          fi
        name: Check DOCKERHUB_USERNAME
    - run:
        command: |
          if [ -z "$DOCKERHUB_PASSWORD" ]; then
            echo "ERROR: DOCKERHUB_PASSWORD is not set!"
            exit 127
          fi
        name: Check DOCKERHUB_PASSWORD
    - when:
        condition: << parameters.organization >>
        steps:
        - envorb/value:
            value: << parameters.organization >>
            variable: DOCKERHUB_ORG
    - unless:
        condition: << parameters.organization >>
        steps:
        - envorb/git_org:
            variable: DOCKERHUB_ORG
    - when:
        condition: << parameters.repository >>
        steps:
        - envorb/value:
            value: << parameters.repository >>
            variable: DOCKERHUB_REPO
    - unless:
        condition: << parameters.repository >>
        steps:
        - envorb/git_name:
            variable: DOCKERHUB_REPO
    - run:
        command: |
          source /usr/local/bin/envload
          export DOCKERHUB_USR=${DOCKERHUB_USERNAME}
          export DOCKERHUB_PWD=${DOCKERHUB_PASSWORD}
          node /app/index.js
        name: Upload README

description: Allows you to push README.md files to the Docker Hub.
orbs:
  envorb: gofunky/envorb@0.3.9
readmyhub_params:
  file:
    default: README.md
    description: Path to the README.md file
    type: string
readmyhub_update_params:
  organization:
    default: ""
    description: |
      Docker Hub organization or user name. Environment variables from envorbs are accepted. By default, the git organization is assumed.
    type: string
  repository:
    default: ""
    description: |
      Docker Hub repository name. Environment variables from envorbs are accepted. By default, the git repository name is assumed.
    type: string
